### ISSUE TITLE
Crash with Magic Doorknob - cannot load mod

### ISSUE THREAD

**Issue by Areolata7** [TBoshoven/MinecraftMods#30] opened 2020-06-14 10:09 UTC
Running 1.14.4 with Forge 28.2.0 and MagicDoorknob-1.14.4-0.0.2.169

Attached is one example of a crash report. As you can see further down the log it says:

MagicDoorknob-1.14.4-0.0.2.169 (1).jar Magic Doorknob {magic_doorknob@1.14.4-0.0.2.169 ERROR}

At the top of the log it mentions Doggy Talents but I have run that mod for a year and can run it perfectly fine with all the other mods listed in my report. Just as a test; I went ahead and removed Doggy Talents and still get the same error mentioning a different mod. So I removed that second mod  (Illuminations) and then get the same crash mentioning a 3rd mod at the top. So what is mentioned at the top of the crash report keeps changing and the only common denominator is Magic Doorknob. The only way to correctly launch the game is to remove Magic Doorknob and leave all the other mods intact.

I also tried to download Magic Doorknob twice to rule out file corruption and neither download worked. 

I would really like to use this mod, it seems really interesting, but I have been unable to get it to work even once. Please advise. Thank you!

[crash-2020-06-14_04.50.11-client.txt](https://github.com/TBoshoven/MinecraftMods/files/4776192/crash-2020-06-14_04.50.11-client.txt)

**Comment by TBoshoven** [comment] 2020-06-15 15:14
Thank you for reporting.

This mod does register block colors, so it might be some weird logging issue pointing at other mods.
However, my code does do proper `null` checks, so I don't see any clear culprit.

I cannot reproduce this using just the Magic Doorknob mod, so to help me pinpoint the issue, can you tell me what the minimal configuration is that triggers this issue?
If you could help me narrow it down to a single other mod or a small set of other mods, that would be very helpful.

**Comment by TBoshoven** [comment] 2020-06-16 00:10
Actually, I managed to reproduce it by just installing Doggy Talents.

Taking a look.

**Comment by TBoshoven** [comment] 2020-06-16 00:24
It seems to be related to percivalalb/DoggyTalents#194 which claims the issue is on my end. This is, of course, very likely. However, the only error messages I see come from that mod.

**Comment by TBoshoven** [comment] 2020-06-16 00:41
Looks like it might be Optifine. At least, I get a crash when installing that (though later than yours it seems).
Don't know why Optifine would break things, but it does some rendering magic and I am also doing some rendering magic.

**Comment by Areolata7** [comment] 2020-06-16 15:18
Okay I will test also. I knew it was not Doggy Talents because I removed that mod and still had issues. I did not consider optifine so I will check. Thank you for looking into this.

**Comment by TBoshoven** [comment] 2020-06-16 22:56
I'm suspecting the Optifine thing might be a red herring as well. The crash I'm seeing is being reported to their issue list, but it doesn't match the crash you're seeing.
I'd be happy to find the exact culprit, but you're running a lot of mods. Do you happen to have them in a CurseForge pack or something easy to download and play with?

**Comment by Areolata7** [comment] 2020-06-17 14:22
I have a slighlty older build for testing that has less mods so I tried Magic Doorknob on it. Instead of simply crashing without warning I got the following message from forge:

![image](https://user-images.githubusercontent.com/56558824/84907357-b3f58e80-b078-11ea-8aa6-29eb72d4fe8b.png)

I tried to attach a zip file with the 18 mods of that build, but it is too big, so the list is below. Optifine is still used so it is still a contender. Please advise. 

Advanced Skin Customization 2.6.2
Almost All The Ores 1.0.0.4
Ambient Sounds v3.0.14
Aquaculture 2.0.3
Bamboo Everything 1.4.0
BetterAnimals 5.2.1
Create v0.2.3
Extended Caves 1.5
Familiar Horses v1.3.1
JEI 6.0.0.27
Magic Doorknob 0.0.2.169
Nomadic Tents 10.1.0
Optfine F5
Simple Farming 1.2.1
WildNature 2.1.6.5
WorldEdit 7.0.1
Xaeros Minimap 20.6.0
(all for MC 1.14)

**Comment by TBoshoven** [comment] 2020-06-17 23:28
I think I have found the issue.
You mentioned using Forge 28.2.0, and I somehow didn't realize this was not the latest version.

The 1.14.4 version of the Magic Doorknob mod depends on a Forge version that is at least 1.14.4-28.2.2 (came out February this year). This contains a a model loading system (made by Gigaherz) that I use to implement the texture-changing model loader.

Can you please try using 28.2.2 or higher (any reason you're not using the latest?) and let me know if that fixes it?

**Comment by TBoshoven** [comment] 2020-08-09 18:09
Closing since I cannot reproduce the issue. Please let me know if it's still not working.

**Closed by TBoshoven** 2020-08-09 18:09 UTC
Labels: minecraft 1.14.4, mod magic doorknob
