### ISSUE TITLE
Light bug

### ISSUE THREAD

**Issue by Prosius** [TBoshoven/MinecraftMods#81] opened 2020-12-22 23:10 UTC
I have a light bug while I am playing my modpack. the player is almost completely white in the mirror. Could Phosphor be the issue? (I am also using Optifine)

**Comment by TBoshoven** [comment] 2020-12-23 01:21
Unfortunately it's hard for me to tell without trying it out.
I do not do any testing with Optifine, so that is a likely culprit.
I don't know about Phosphor. I figured that would only do chunk lighting and the mirror reflection is rendered before the world in most versions of this mod. Also keep in mind that if this is a Phosphor issue, I think the Forge version is no longer maintained.

I could give it a shot. I have been getting questions about Optifine.
Please let me know the following:
* Your Minecraft version
* Your Optifine version
* Your Phosphor version

If possible, also add a screenshot so I know what I'm looking for.

**Comment by Prosius** [comment] 2020-12-23 01:27
Thanks! And cool that you test and try to improve your mod like that.
1.15.2, preview_OptiFine_1.15.2_HD_U_G5_pre1, phosphor-forge-mc1.15.2-0.5.2+build.4
I will add tomorrow a screenshot.

**Comment by TBoshoven** [comment] 2020-12-23 04:18
I just gave it a shot and could not reproduce any light issues using the given configuration with their default settings.
![2020-12-22_23 05 52](https://user-images.githubusercontent.com/1949124/102958301-8fa4bf80-44aa-11eb-8740-8f924e550cd8.png)
![2020-12-22_23 06 11](https://user-images.githubusercontent.com/1949124/102958322-959aa080-44aa-11eb-9c17-353aed961eb2.png)
![2020-12-22_23 06 47](https://user-images.githubusercontent.com/1949124/102958327-98959100-44aa-11eb-90a3-0c36467d3949.png)
My Forge version is not the most recent (it's what I happened to have on my test installation) but I doubt that is the problem.

Unfortunately I do not have the time to help you debug your mod pack, but I'd encourage you to temporarily disable some mods (both Optifine and Phosphor should be safe to disable or remove) to try and reproduce the issue.

It could also help to place a mirror in a freshly generated part of the world. Rendering issues are often caused by a combination of blocks being rendered.

Please let me know if you find the culprit so I can help get things working :)

**Comment by Prosius** [comment] 2020-12-28 03:37
it was probably some bug with phosphor. i tried it without it without and there was no bug anymore.

**Comment by TBoshoven** [comment] 2020-12-28 16:46
I see. Since I could not reproduce the bug with the version of Phosphor you were using, please provide me with some more details so I can reproduce it and fix the issue. Keep in mind that the Phosphor is no longer maintained for Forge, so I may not be able to fix it if it requires changes on their side.

If you'd prefer to consider this issue resolved, please close it.

**Closed** 2021-01-18 22:43 UTC
Labels: bug, minecraft 1.15.2, mod magic mirror
